### ISSUE TITLE
Creating a SyncPlay group in Jellyfin MPV Desktop breaks the SyncPlay feature for all users of that Jellyfin server

### ISSUE THREAD

**Issue by whalehub** [iwalton3/jellyfin-mpv-shim#107]
**Describe the bug**
When you create a SyncPlay group in Jellyfin MPV Desktop by either using the menu option and then playing something or by playing something and then using the menu option (the order doesn't seem to matter), users who click on the SyncPlay icon in their client receive the error message "An error occurred while accessing groups list." This not only prevents other users from joining your SyncPlay group, it also makes it impossible for them to create their own group, effectively breaking the SyncPlay feature server-wide.

**To Reproduce**
1. Open Jellyfin MPV Desktop on one computer (C1) and either the Jellyfin web client or a second instance of Jellyfin MPV Desktop on another computer (C2).
2. Create a SyncPlay group on C1 and play back a movie or TV show episode (or vice versa).
3. Click on the SyncPlay icon on C2.
4. See error message.

**Expected behavior**
Users who click on the SyncPlay icon see the group that was created in Jellyfin MPV Desktop in the drop-down menu and can choose to either join it or create their own SyncPlay group.

**Screenshots**

![error](https://xbb.datahoarder.dev/VUSu3/vEKAhUri16.png/raw)

**Desktop**
 - **OS:** Windows
 - **Version:** 1.8.0

**Error messages**
The log file is not updated with any new information after creating a SyncPlay group with logging enabled in the config file.

**Additional notes**
Jellyfin MPV Desktop can join a SyncPlay group that was created by another user in the Jellyfin web client without any issues.

**Comment by iwalton3** [comment]
Creating a SyncPlay group via the Desktop client is not possible due to a current insufficency with the API. You have to create the group within MPV using the `c` menu.

I have confirmed the denial of service related issue is a problem with the Jellyfin server. Leaving the group from the desktop client fixes the issue. While I could patch out the button to join a group from the desktop client, it is also be an issue if someone is casting to a player from the web app and they hit that button.

```
[2020-08-18 09:24:43.359 -04:00] [ERR] Error processing request. URL: "http://[domain]/SyncPlay/List"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.SyncPlay.SyncPlayController.GetPlayingItemId()
   at Emby.Server.Implementations.SyncPlay.SyncPlayManager.<>c__DisplayClass21_0.<ListGroups>b__2(ISyncPlayController group)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at Emby.Server.Implementations.SyncPlay.SyncPlayManager.ListGroups(SessionInfo session, Guid filterItemId)
   at MediaBrowser.Api.SyncPlay.SyncPlayService.Get(SyncPlayList request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```
I have created this upstream issue: https://github.com/jellyfin/jellyfin/issues/3931

**Comment by whalehub** [comment]
@iwalton3 Thanks for the workaround!

**Comment by iwalton3** [comment]
This is not present in the new release candidate.
