### ISSUE TITLE
Authentification Error

### ISSUE THREAD

**Issue by kernitus** [iwalton3/jellyfin-mpv-shim#12]
**Describe the bug**
I am unable to authenticate with my Jellyfin server, getting an Internal Server Error.

**To Reproduce**
1. Add the server
2. Error

**Expected behavior**
Successful authentification after adding the server

**Desktop:**
 - OS: Arch Linux
 - Version 5.4.15-arch1-1

**Error Messages**
https://pastebin.com/00GxRWwm

**Potentially relevant:**
The server is running Jellyfin behind a reverse proxy that points to the jellyfin subdomain.

**Comment by iwalton3** [comment]
What reverse proxy are you using?
Can you provide logs for the reverse proxy and Jellyfin server that indicates where the 500 is coming from?
Are you running the server on a sub-directory? (From the log it appears the answer is no.)

**Comment by darkermatter** [comment]
Here's some output from running in the shell:
```
2020-02-03 15:55:54,268 [   DEBUG] Starting new HTTPS connection (1): blurred.out:443
2020-02-03 15:55:54,414 [   DEBUG] https://blurred.out:443 "POST /Users/AuthenticateByName HTTP/1.1" 302 0
2020-02-03 15:55:54,453 [   DEBUG] https://blurred.out:443 "GET /jellyfin/web/index.html HTTP/1.1" 200 None
2020-02-03 15:55:54,459 [   ERROR] Error while adding server.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_mpv_shim/gui_mgr.py", line 170, in run
    is_logged_in = clientManager.login(*param)
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_mpv_shim/clients.py", line 93, in login
    client.auth.login(server, username, password)
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_apiclient_python/connection_manager.py", line 116, in login
    self._on_authenticated(result, options)
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_apiclient_python/connection_manager.py", line 461, in _on_authenticated
    self.config.data['auth.user_id'] = result['User']['Id']
TypeError: 'NoneType' object is not subscriptable
```
Here's what I have for reverse proxy in Apache2:
```
<VirtualHost *:443>
    ServerName blurred.out
    SSLEngine On
    SSLCertificateFile /etc/ssl/certs/blurred.out.crt
    SSLCertificateKeyFile /etc/ssl/private/blurred.out.key
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerCN off

    RewriteEngine on
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule .* "ws://localhost:8096%{REQUEST_URI}" [P]

    ProxyRequests off
    ProxyPreserveHost on
    ProxyPass                   / http://localhost:8096/
    ProxyPassReverse    / http://localhost:8096/
    <Proxy *>
          Order deny,allow
          Allow from all
    </Proxy>
</VirtualHost>
```
Here's some log output from Apache2:
```
==> /var/log/apache2/other_vhosts_access.log <==
blurred.out:443 192.168.144.49 - - [03/Feb/2020:16:03:37 +0100] "GET /system/info/public HTTP/1.1" 302 3474 "-" "python-requests/2.21.0"                                            
blurred.out:443 192.168.144.49 - - [03/Feb/2020:16:03:37 +0100] "GET /jellyfin/web/index.html HTTP/1.1" 200 2452 "-" "python-requests/2.21.0"                                       
blurred.out:443 192.168.144.49 - - [03/Feb/2020:16:03:38 +0100] "GET /system/info/public HTTP/1.1" 302 3474 "-" "python-requests/2.21.0"                                            
blurred.out:443 192.168.144.49 - - [03/Feb/2020:16:03:38 +0100] "GET /jellyfin/web/index.html HTTP/1.1" 200 2452 "-" "python-requests/2.21.0"                                       
blurred.out:443 192.168.144.49 - - [03/Feb/2020:16:03:38 +0100] "POST /Users/AuthenticateByName HTTP/1.1" 302 3474 "-" "Jellyfin-MPV-Shim/1.3.4"                                    
blurred.out:443 192.168.144.49 - - [03/Feb/2020:16:03:38 +0100] "GET /jellyfin/web/index.html HTTP/1.1" 200 2452 "-" "Jellyfin-MPV-Shim/1.3.4"                                      
```

**Comment by iwalton3** [comment]
It looks like the player is getting redirected to `/jellyfin/web/index.html` when it makes API requests. Maybe try connecting with `https://blurred.out/jellyfin`?

**Comment by darkermatter** [comment]
Okay I tried adding `/jellyfin` and got registered. 

Now, when I play back I get this:
```
2020-02-03 17:00:21,008 [   DEBUG] https://blurred.out:443 "GET /jellyfin/Users/b6316f230aa74f24a6fd45215390a46c/Items/4b2fc6690540278079393dc2a45842e9 HTTP/1.1" 200 None
2020-02-03 17:00:21,016 [   DEBUG] EventHandler::playMedia <jellyfin_mpv_shim.media.Media object at 0x7fe9d85d1a10>
2020-02-03 17:00:21,040 [   DEBUG] https://blurred.out:443 "POST /jellyfin/Items/4b2fc6690540278079393dc2a45842e9/PlaybackInfo HTTP/1.1" 200 None
2020-02-03 17:00:21,607 [   DEBUG] PlayerManager::play selecting audio stream index=1
2020-02-03 17:00:21,607 [   DEBUG] PlayerManager::play selecting subtitle stream index=4
2020-02-03 17:00:21,693 [   DEBUG] https://blurred.out:443 "POST /jellyfin/Sessions/Playing HTTP/1.1" 204 0
2020-02-03 17:00:21,762 [   DEBUG] https://blurred.out:443 "POST /jellyfin/Sessions/Playing/Progress HTTP/1.1" 204 0
2020-02-03 17:00:22,271 [   DEBUG] Unhandled Event UserDataChanged: {'UserId': 'b6316f230aa74f24a6fd45215390a46c', 'UserDataList': [{'PlaybackPositionTicks': 0, 'PlayCount': 11, 'IsFavo$ite': False, 'LastPlayedDate': '2020-02-03T16:00:21.6152159Z', 'Played': False, 'Key': '72449008001', 'ItemId': '4b2fc6690540278079393dc2a45842e9'}, {'UnplayedItemCount': 20, 'PlaybackP$sitionTicks': 0, 'PlayCount': 0, 'IsFavorite': False, 'Played': False, 'Key': '72449008', 'ItemId': 'a54d6b6aaed7e76b340c57a59722d01b'}], 'ServerId': 'a16c121a6b174e2fb53180f3214ffaf7'}
2020-02-03 17:00:28,464 [   DEBUG] Starting new HTTPS connection (2): blurred.out:443
2020-02-03 17:00:29,854 [   DEBUG] https://blurred.out:443 "GET /jellyfin/Sessions/Playing/Progress HTTP/1.1" 404 None
404 Client Error: Not Found for url: https://blurred.out/jellyfin/Sessions/Playing/Progress
2020-02-03 17:00:29,860 [   ERROR] 404 Client Error: Not Found for url: https://blurred.out/jellyfin/Sessions/Playing/Progress
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_apiclient_python/http.py", line 106, in request
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://media.onecha.net/jellyfin/Sessions/Playing/Progress

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_mpv_shim/timeline.py", line 28, in run
    self.SendTimeline()
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_mpv_shim/timeline.py", line 42, in SendTimeline
    playerManager.send_timeline()
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_mpv_shim/utils.py", line 40, in _synchronizer
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_mpv_shim/player.py", line 477, in send_timeline
    self._video.client.jellyfin.session_progress(self.get_timeline_options())
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_apiclient_python/api.py", line 319, in session_progress
    return self.sessions("/Playing/Progress", "POST", json=data)
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_apiclient_python/api.py", line 72, in sessions
    return self._post("Sessions%s" % handler, json, params)
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_apiclient_python/api.py", line 53, in _post
    return self._http("POST", handler, {'params': params, 'json': json})
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_apiclient_python/api.py", line 42, in _http
    return self.client.request(request)
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_apiclient_python/http.py", line 161, in request
    raise HTTPException(r.status_code, error)
jellyfin_apiclient_python.exceptions.HTTPException: (404, HTTPError('404 Client Error: Not Found for url: https://media.onecha.net/jellyfin/Sessions/Playing/Progress'))
```
Jellyfin version: 10.4.3

**Comment by darkermatter** [comment]
You are right. I found out from the release notes here https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1 that there is a problem with the sub-paths and a manual fix is required. I patched the configuration in the Docker container and it works perfectly now!

Thanks for a great addition to Jellyfin. Plex is gone!
