### ISSUE TITLE
Cannot connect to server for jellyfin version 10.7.0

### ISSUE THREAD

**Issue by FadedCoder** [iwalton3/jellyfin-mpv-shim#125]
**Describe the bug**
Not able to connect to the server with IP/domain name. Shows "Could not add server".

**To Reproduce**
1. Install jellyfin v10.7.0 (currently 'unstable' tag on Docker)
2. Try to add server
3. See error

**Expected behavior**
Being able to add server and use this.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.8.0

**Error Messages**
```
2020-09-28 21:19:36,601 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.client: JellyfinClient initializing...
2020-09-28 21:19:36,601 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Configuration initializing...
2020-09-28 21:19:36,601 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin http constructor.
2020-09-28 21:19:36,601 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.ws_client: WSClient initializing...
2020-09-28 21:19:36,601 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: ConnectionManager initializing...
2020-09-28 21:19:36,601 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: Credentials initializing...
2020-09-28 21:19:36,601 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin app constructor.
2020-09-28 21:19:36,601 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2020-09-28 21:19:36,601 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: 5
2020-09-28 21:19:36,601 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: {'Accept': 'application/json', 'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8', 'X-Application': 'Jellyfin MPV Shim/1.8.0', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin-MPV-Shim/1.8.0', 'x-emby-authorization': 'MediaBrowser Client=Jellyfin MPV Shim, Device=Shinobu, DeviceId=df51640b-117a-434f-b7bc-672d06300b6e, Version=1.8.0'}
2020-09-28 21:19:36,603 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): 192.168.1.53:8096
2020-09-28 21:19:36,606 [   DEBUG] urllib3.connectionpool: http://192.168.1.53:8096 "GET /system/info/public HTTP/1.1" 200 None
2020-09-28 21:19:36,607 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: connectToAddress http://192.168.1.53:8096 succeeded
2020-09-28 21:19:36,607 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: begin connectToServer
2020-09-28 21:19:36,607 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2020-09-28 21:19:36,607 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: 5
2020-09-28 21:19:36,607 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: {'Accept': 'application/json', 'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8', 'X-Application': 'Jellyfin MPV Shim/1.8.0', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin-MPV-Shim/1.8.0', 'x-emby-authorization': 'MediaBrowser Client=Jellyfin MPV Shim, Device=Shinobu, DeviceId=df51640b-117a-434f-b7bc-672d06300b6e, Version=1.8.0'}
2020-09-28 21:19:36,608 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): 192.168.1.53:8096
2020-09-28 21:19:36,611 [   DEBUG] urllib3.connectionpool: http://192.168.1.53:8096 "GET /system/info/public HTTP/1.1" 200 None
2020-09-28 21:19:36,611 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: calling onSuccessfulConnection with server None
2020-09-28 21:19:36,611 [    INFO] JELLYFIN.jellyfin_apiclient_python.credentials: None
2020-09-28 21:19:36,611 [ WARNING] JELLYFIN.jellyfin_apiclient_python.credentials: invalid credentials format
2020-09-28 21:19:36,611 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: credentials initialized with: {}
2020-09-28 21:19:36,612 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: credentialsupdated
2020-09-28 21:19:36,612 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Trying to login to http://192.168.1.53:8096/Users/AuthenticateByName as ghost
2020-09-28 21:19:36,612 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending post request to Users/AuthenticateByName
2020-09-28 21:19:36,612 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: (5, 30)
2020-09-28 21:19:36,612 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: {'Accept': 'application/json', 'Content-type': 'application/json', 'X-Application': 'Jellyfin MPV Shim/1.8.0', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin-MPV-Shim/1.8.0', 'x-emby-authorization': 'MediaBrowser Client=Jellyfin MPV Shim, Device=Shinobu, DeviceId=df51640b-117a-434f-b7bc-672d06300b6e, Version=1.8.0'}
2020-09-28 21:19:36,613 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): 192.168.1.53:8096
2020-09-28 21:19:36,920 [   DEBUG] urllib3.connectionpool: http://192.168.1.53:8096 "POST /Users/AuthenticateByName HTTP/1.1" 200 None
2020-09-28 21:19:36,921 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Succesfully logged in as ghost
2020-09-28 21:19:36,921 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.client: JellyfinClient initializing...
2020-09-28 21:19:36,921 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Configuration initializing...
2020-09-28 21:19:36,921 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin http constructor.
2020-09-28 21:19:36,921 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.ws_client: WSClient initializing...
2020-09-28 21:19:36,921 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: ConnectionManager initializing...
2020-09-28 21:19:36,921 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: Credentials initializing...
2020-09-28 21:19:36,921 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin app constructor.
2020-09-28 21:19:36,921 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin connect
2020-09-28 21:19:36,922 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin getAvailableServers
2020-09-28 21:19:36,922 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: MultiGroup      : ('<broadcast>', 7359)
2020-09-28 21:19:36,922 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: Sending UDP Data: b'who is JellyfinServer?'
2020-09-28 21:19:37,503 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.ws_client: Ignoring {'MessageType': 'RefreshProgress', 'MessageId': '76aebbe9-1b9f-46c1-bdbf-44e37537d2f5', 'Data': "{'ItemId': 'e51479848f016b7ccd0d57fa4b8e9fa8', 'Progress': '94.70748299319727'}"}
2020-09-28 21:19:37,518 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.ws_client: Ignoring {'MessageType': 'RefreshProgress', 'MessageId': '30be15cd-1484-423b-87c2-f34ebdde2b4b', 'Data': "{'ItemId': '0c41907140d802bb58430fed7e2cd79e', 'Progress': '94.70748299319727'}"}
2020-09-28 21:19:37,922 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Found Servers: []
2020-09-28 21:19:37,922 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: credentialsupdated
2020-09-28 21:19:37,922 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: connect has 1 servers
2020-09-28 21:19:37,922 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: begin connectToServer
2020-09-28 21:19:37,922 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2020-09-28 21:19:37,922 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: 5
2020-09-28 21:19:37,922 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: {'Accept': 'application/json', 'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8', 'X-Application': 'Jellyfin MPV Shim/1.8.0', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin-MPV-Shim/1.8.0', 'x-emby-authorization': 'MediaBrowser Client=Jellyfin MPV Shim, Device=Shinobu, DeviceId=df51640b-117a-434f-b7bc-672d06300b6e, Version=1.8.0'}
2020-09-28 21:19:37,923 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): 192.168.1.53:8096
2020-09-28 21:19:37,927 [   DEBUG] urllib3.connectionpool: http://192.168.1.53:8096 "GET /system/info/public HTTP/1.1" 200 None
2020-09-28 21:19:37,927 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: calling onSuccessfulConnection with server aqua
2020-09-28 21:19:37,927 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info
2020-09-28 21:19:37,928 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: 5
2020-09-28 21:19:37,928 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: {'Accept': 'application/json', 'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8', 'X-Application': 'Jellyfin MPV Shim/1.8.0', 'Accept-Charset': 'UTF-8,*', 'Accept-encoding': 'gzip', 'User-Agent': 'Jellyfin-MPV-Shim/1.8.0', 'x-emby-authorization': 'MediaBrowser Client=Jellyfin MPV Shim, Device=Shinobu, DeviceId=df51640b-117a-434f-b7bc-672d06300b6e, Version=1.8.0', 'X-MediaBrowser-Token': 'REDACTED'}
2020-09-28 21:19:37,929 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): 192.168.1.53:8096
2020-09-28 21:19:37,976 [   DEBUG] urllib3.connectionpool: http://192.168.1.53:8096 "GET /system/info HTTP/1.1" 200 None
2020-09-28 21:19:37,976 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: credentialsupdated
2020-09-28 21:19:37,977 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: resolving connect with result: {'Servers': "[{'address': 'http://192.168.1.53:8096', 'Name': 'aqua', 'Id': '81c63a223c5d4aeb8b6958837cc7c488', 'DateLastAccessed': '2020-09-28T21:19:37Z', 'UserId': 'e73d1349-9491-4e0f-904a-03ccb213139b', 'AccessToken': 'REDACTED', 'Users': [{'Id': 'e73d1349-9491-4e0f-904a-03ccb213139b', 'IsSignedInOffline': True}], 'uuid': '46819c8a-059a-4274-9fe6-6db700d9f8c7', 'username': 'ghost'}]", 'State': 3}
2020-09-28 21:19:37,977 [    INFO] JELLYFIN.jellyfin_apiclient_python.client: User is authenticated.
2020-09-28 21:19:37,977 [   DEBUG] urllib3.util.retry: Converted retries value: 3 -> 'Retry(total=3, connect=None, read=None, redirect=None, status=None)'
2020-09-28 21:19:37,977 [   DEBUG] urllib3.util.retry: Converted retries value: 3 -> 'Retry(total=3, connect=None, read=None, redirect=None, status=None)'
2020-09-28 21:19:37,977 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: Websocket url: ws://192.168.1.53:8096/socket?api_key=REDACTEDREDACTED&device_id=df51640b-117a-434f-b7bc-672d06300b6e
2020-09-28 21:19:37,979 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): 192.168.1.53:8096
2020-09-28 21:19:38,012 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: --->[ websocket ]
2020-09-28 21:19:38,012 [   DEBUG] event_handler: Unhandled Event WebSocketConnect: None
2020-09-28 21:19:38,015 [   DEBUG] urllib3.connectionpool: http://192.168.1.53:8096 "POST /Sessions/Capabilities/Full HTTP/1.1" 400 None
2020-09-28 21:19:38,016 [   ERROR] Jellyfin.jellyfin_apiclient_python.http: 400 Client Error: Bad Request for url: http://192.168.1.53:8096/Sessions/Capabilities/Full
2020-09-28 21:19:38,016 [   ERROR] gui_mgr: Error while adding server.
Traceback (most recent call last):
  File "jellyfin_apiclient_python\http.py", line 107, in request
  File "requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://192.168.1.53:8096/Sessions/Capabilities/Full

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jellyfin_mpv_shim\gui_mgr.py", line 168, in run
  File "jellyfin_mpv_shim\clients.py", line 131, in login
  File "jellyfin_mpv_shim\clients.py", line 186, in _connect_client
  File "jellyfin_mpv_shim\clients.py", line 160, in setup_client
  File "jellyfin_apiclient_python\api.py", line 333, in post_capabilities
  File "jellyfin_apiclient_python\api.py", line 81, in sessions
  File "jellyfin_apiclient_python\api.py", line 62, in _post
  File "jellyfin_apiclient_python\api.py", line 51, in _http
  File "jellyfin_apiclient_python\http.py", line 162, in request
jellyfin_apiclient_python.exceptions.HTTPException: (400, HTTPError('400 Client Error: Bad Request for url: http://192.168.1.53:8096/Sessions/Capabilities/Full'))
```

**Comment by iwalton3** [comment]
> jellyfin_apiclient_python.exceptions.HTTPException: (400, HTTPError('400 Client Error: Bad Request for url: http://192.168.1.53:8096/Sessions/Capabilities/Full'))

Please provide the corresponding server logs that generated the 400 response for `http://192.168.1.53:8096/Sessions/Capabilities/Full`.

**Comment by FadedCoder** [comment]
> > jellyfin_apiclient_python.exceptions.HTTPException: (400, HTTPError('400 Client Error: Bad Request for url: http://192.168.1.53:8096/Sessions/Capabilities/Full'))
> 
> Please provide the corresponding server logs that generated the 400 response for `http://192.168.1.53:8096/Sessions/Capabilities/Full`.

```
[16:27:23] [INF] [73] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for ghost has succeeded.
[16:27:23] [INF] [73] Emby.Server.Implementations.Session.SessionManager: Reissuing access token: <ACCESS TOKEN>
[16:27:24] [INF] [117] Emby.Server.Implementations.HttpServer.WebSocketManager: WS ::ffff:192.168.1.101 request
```

**Comment by iwalton3** [comment]
I don't see anything relating to the 400 error in the log. Could you provide the entire log file?

**Comment by FadedCoder** [comment]
> I don't see anything relating to the 400 error in the log. Could you provide the entire log file?

Hm that's the entire log I got from doing `docker logs`. Is there any other log?

**Comment by iwalton3** [comment]
I would expect to see something that includes the URL that threw the error. Something like this:

```
[2020-09-28 12:23:15.481 -04:00] [ERR] Error processing request. URL: "http://example.com/Items/6d046f4c4ab73327b5c28af9295b3b4b/Images/Backdrop/0?tag=6d046f4c4ab73327b5c28af9295b3b4b"
System.ArgumentException: Unable to determine image file extension from mime type text/html
   at MediaBrowser.Providers.Manager.ImageSaver.GetStandardSavePath(BaseItem item, ImageType type, Nullable`1 imageIndex, String mimeType, Boolean saveLocally)
   at MediaBrowser.Providers.Manager.ImageSaver.GetSavePaths(BaseItem item, ImageType type, Nullable`1 imageIndex, String mimeType, Boolean saveLocally)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImage(BaseItem item, Stream source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at MediaBrowser.Api.Images.ImageService.GetImageResult(BaseItem item, Guid itemId, ImageRequest request, ItemImageInfo image, Boolean cropwhitespace, IReadOnlyCollection`1 supportedFormats, Nullable`1 cacheDuration, IDictionary`2 headers, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

Usually Jellyfin writes logs to a log directory. You should be able to access it from the directory where you configured Jellyfin to store data using docker.

**Comment by FadedCoder** [comment]
> I would expect to see something that includes the URL that threw the error. Something like this:
> 
> ```
> [2020-09-28 12:23:15.481 -04:00] [ERR] Error processing request. URL: "http://example.com/Items/6d046f4c4ab73327b5c28af9295b3b4b/Images/Backdrop/0?tag=6d046f4c4ab73327b5c28af9295b3b4b"
> System.ArgumentException: Unable to determine image file extension from mime type text/html
>    at MediaBrowser.Providers.Manager.ImageSaver.GetStandardSavePath(BaseItem item, ImageType type, Nullable`1 imageIndex, String mimeType, Boolean saveLocally)
>    at MediaBrowser.Providers.Manager.ImageSaver.GetSavePaths(BaseItem item, ImageType type, Nullable`1 imageIndex, String mimeType, Boolean saveLocally)
>    at MediaBrowser.Providers.Manager.ImageSaver.SaveImage(BaseItem item, Stream source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
>    at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
>    at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
>    at MediaBrowser.Api.Images.ImageService.GetImageResult(BaseItem item, Guid itemId, ImageRequest request, ItemImageInfo image, Boolean cropwhitespace, IReadOnlyCollection`1 supportedFormats, Nullable`1 cacheDuration, IDictionary`2 headers, Boolean isHeadRequest)
>    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
>    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
>    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
> ```
> 
> Usually Jellyfin writes logs to a log directory. You should be able to access it from the directory where you configured Jellyfin to store data using docker.

I checked the log files but there's no ERR logging. Seems like it errors out only on client side.

**Comment by iwalton3** [comment]
It looks like the log files would be in one of the persistent volumes. https://jellyfin.org/docs/general/administration/installing.html#docker

I _really_ need logs from the server for this one, otherwise I'll likely need to wait until someone else has this problem or 10.7.0 is released.

**Comment by wwwutz** [comment]
Same problem here with server running git master:

fresh install of ubuntu 20.4 on odroid c4, `jellyfin-mpv-shim` install.

1. start up jellyfin-mpv-shim
2. enter server `192.168.1.7`, username `gast`, no password
3. press `Add server` button
4. *bang*
5. requester opens up with "Could not add server. Please check your connection information."
6. Last line on console: `jellyfin_apiclient_python.exceptions.HTTPException: (400, HTTPError('400 Client Error: Bad Request for url: http://192.168.1.7:8096/Sessions/Capabilities/Full'))`

error log on console:
 
[shim-fail.log](https://github.com/iwalton3/jellyfin-mpv-shim/files/5322968/shim-fail.log)

error log on jellyfin-server: ( removed some websocket-bla spam )

[jellyfin20201004.log](https://github.com/iwalton3/jellyfin-mpv-shim/files/5322977/jellyfin20201004.log)

**Comment by iwalton3** [comment]
Neat. So from the server it looks ethereal client just drops the connection. There is no logging of the failed endpoint at all.

Does the Kodi plugin work?

**Comment by iwalton3** [comment]
Further information seems to suggest breakage of the `/Session/Capabilities/Full`. It doesn't end up in the logs because it is a deserializer error.

The message, after enabling debug logging is:
```
[19:13:12] [DBG] [251] Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter: JSON input formatter threw an exception: The JSON value could not be converted to System.String[]. Path: $.PlayableMediaTypes | LineNumber: 0 | BytePositionInLine: 30.
```
Which seems to suggest that the `PlayableMediaTypes` field has had the type changed from string (comma delimited) to string[].

**Comment by iwalton3** [comment]
Also, since the Kodi client uses the same API client and makes the same call, it likely is broken by this as well.

**Comment by ddonindia** [comment]
I am also facing the same issue.  Is there any workaround for this issue ?

**Comment by wwwutz** [comment]
bisected master and ended up at
```
wwwutz@eldersoftheinternet:jellyfin ((e9c9fc436...)|BISECTING)$ git bisect good
e7f55c5110adea7092b8965a1c0fc45bc7cd0453 is the first bad commit
commit e7f55c5110adea7092b8965a1c0fc45bc7cd0453
Author: crobibero <cody@robibe.ro>
Date:   Sun Aug 9 13:51:25 2020 -0600

    Fix Requirement assigned to Handler

 .../FirstTimeOrIgnoreParentalControlSetupHandler.cs                  | 5 ++---
 1 file changed, 2 insertions(+), 3 deletions(-)

```

**Comment by wwwutz** [comment]
> I am also facing the same issue. Is there any workaround for this issue ?

```
git revert e7f55c5110adea7092b8965a1c0fc45bc7cd0453
```

does the trick on current jellyfin master

might break other stuff 8-)

**Comment by wwwutz** [comment]
Hmmm... OK, failed to connect io s gone, the server has been added, but there's still no connection to the server.

**Comment by iwalton3** [comment]
Update: This should be fixed once https://github.com/jellyfin/jellyfin/pull/4292 is merged.

**Comment by iwalton3** [comment]
That PR didn't actually fix all of the issues. There are a few other changes in 10.7.0 that are currently breaking MPV Shim. I was told however that there is no intent to break the API for now, so they will likely be fixed before release. Obviously if they aren't then I'll make arrangements to deal with them.

**Comment by iwalton3** [comment]
This has been fixed by upstream.
