### ISSUE TITLE
Missing installed dependencies after installing from pypi in Buster

### ISSUE THREAD

**Issue by topas-rec** [iwalton3/jellyfin-mpv-shim#136]
**Describe the bug**
Install via PyPi as mentioned [here](https://github.com/iwalton3/jellyfin-mpv-shim/issues/59#issuecomment-712271154) and launch it (see log)

**To Reproduce**
```
tobias@tobias-pc:~$ pip --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
tobias@tobias-pc:~$ pip search jellyfin
Jellyfin-CLI (1.5)                 - A Jellyfin command line client.
jellyfin-accounts (0.3.9)          - A simple account management system for Jellyfin
Mopidy-Jellyfin (1.0.1)            - Mopidy extension for playing music from jellyfin
jellyfin-apiclient-python (1.6.2)  - Python API client for Jellyfin
  INSTALLED: 1.6.1
  LATEST:    1.6.2
jellyfin (0.0.0)                   - 
jellyfin-mpv-shim (1.8.0)          - Cast media from Jellyfin Mobile and Web apps to MPV.
                                     (Unofficial)
jellyfin-build (0.0.0)             - 
jprm (0.3.1)                       - Jellyfin Plugin Repository Manager
jfmp (0.0.1)                       - A minimalist cross-platform gapless music player for Jellyfin
tobias@tobias-pc:~$ pip install jellyfin-mpv-shim 
Collecting jellyfin-mpv-shim
  Downloading https://files.pythonhosted.org/packages/b0/9c/f54be0e96c9b10f5c570da0bb746e734d9e8eb9cf6c02bfd37d1fce1044b/jellyfin_mpv_shim-1.8.0-py3-none-any.whl (37.8MB)
    100% |████████████████████████████████| 37.8MB 49kB/s 
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from jellyfin-mpv-shim) (2.21.0)
Requirement already satisfied: jellyfin-apiclient-python>=1.6.1 in ./.local/lib/python3.7/site-packages (from jellyfin-mpv-shim) (1.6.1)
Requirement already satisfied: python-mpv in ./.local/lib/python3.7/site-packages (from jellyfin-mpv-shim) (0.5.2)
Requirement already satisfied: python-mpv-jsonipc>=1.1.9 in ./.local/lib/python3.7/site-packages (from jellyfin-mpv-shim) (1.1.11)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from jellyfin-apiclient-python>=1.6.1->jellyfin-mpv-shim) (1.24.1)
Requirement already satisfied: websocket-client in ./.local/lib/python3.7/site-packages (from jellyfin-apiclient-python>=1.6.1->jellyfin-mpv-shim) (0.57.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from jellyfin-apiclient-python>=1.6.1->jellyfin-mpv-shim) (1.12.0)
Installing collected packages: jellyfin-mpv-shim
Successfully installed jellyfin-mpv-shim-1.8.0
tobias@tobias-pc:~$ jellyfin-mpv-
jellyfin-mpv-desktop  jellyfin-mpv-shim     
tobias@tobias-pc:~$ jellyfin-mpv-shim 
2020-11-23 17:13:07,765 [    INFO] conf: Loaded settings from json: /home/tobias/.config/jellyfin-mpv-shim/conf.json
Traceback (most recent call last):
  File "/home/tobias/.local/bin/jellyfin-mpv-shim", line 10, in <module>
    sys.exit(main())
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 64, in main
    from .player import playerManager
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/player.py", line 36, in <module>
    import mpv
ModuleNotFoundError: No module named 'mpv'
tobias@tobias-pc:~$ jellyfin-mpv-desktop 
2020-11-23 17:13:18,135 [    INFO] conf: Loaded settings from json: /home/tobias/.config/jellyfin-mpv-shim/conf.json
Traceback (most recent call last):
  File "/home/tobias/.local/bin/jellyfin-mpv-desktop", line 10, in <module>
    sys.exit(main_desktop())
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 106, in main_desktop
    main(desktop, cef)
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 42, in main
    from .webclient_view import WebviewClient
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/webclient_view/__init__.py", line 4, in <module>
    from werkzeug.serving import make_server
ModuleNotFoundError: No module named 'werkzeug'
tobias@tobias-pc:~$ pip install werkzeug
Collecting werkzeug
  Downloading https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl (298kB)
    100% |████████████████████████████████| 307kB 3.0MB/s 
Installing collected packages: werkzeug
Successfully installed werkzeug-1.0.1
tobias@tobias-pc:~$ jellyfin-mpv-shim 
2020-11-23 17:13:42,416 [    INFO] conf: Loaded settings from json: /home/tobias/.config/jellyfin-mpv-shim/conf.json
Traceback (most recent call last):
  File "/home/tobias/.local/bin/jellyfin-mpv-shim", line 10, in <module>
    sys.exit(main())
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 64, in main
    from .player import playerManager
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/player.py", line 36, in <module>
    import mpv
ModuleNotFoundError: No module named 'mpv'
tobias@tobias-pc:~$ pip install werkzeug mpv
Requirement already satisfied: werkzeug in ./.local/lib/python3.7/site-packages (1.0.1)
Collecting mpv
  Downloading https://files.pythonhosted.org/packages/96/ed/ead27053ecf595f03f8c24f5eb1ade16813d9c7b3422bfd6afcef665699b/mpv-0.1.tar.gz
Building wheels for collected packages: mpv
  Running setup.py bdist_wheel for mpv ... done
  Stored in directory: /home/tobias/.cache/pip/wheels/a4/3f/9b/db36a045436f634605b04a034df2344a32463d800b8e21da29
Successfully built mpv
Installing collected packages: mpv
Successfully installed mpv-0.1
tobias@tobias-pc:~$ jellyfin-mpv-shim 
2020-11-23 17:14:06,624 [    INFO] conf: Loaded settings from json: /home/tobias/.config/jellyfin-mpv-shim/conf.json
2020-11-23 17:14:06,646 [ WARNING] player: Could not find libmpv1.
2020-11-23 17:14:06,647 [    INFO] player: Using external mpv playback backend.
2020-11-23 17:14:06,647 [   DEBUG] mpv-jsonipc: Staring MPV from mpv.
2020-11-23 17:14:06,647 [   DEBUG] mpv-jsonipc: Using IPC socket /tmp/mpv31743036763222 for MPV.
Traceback (most recent call last):
  File "/home/tobias/.local/bin/jellyfin-mpv-shim", line 10, in <module>
    sys.exit(main())
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 64, in main
    from .player import playerManager
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/player.py", line 759, in <module>
    playerManager = PlayerManager()
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/player.py", line 151, in __init__
    loglevel=settings.mpv_log_level, **mpv_options)
  File "/home/tobias/.local/lib/python3.7/site-packages/python_mpv_jsonipc.py", line 411, in __init__
    self.mpv_process = MPVProcess(ipc_socket, mpv_location, **kwargs)
  File "/home/tobias/.local/lib/python3.7/site-packages/python_mpv_jsonipc.py", line 217, in __init__
    self.process = subprocess.Popen(args)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mpv': 'mpv'
^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
tobias@tobias-pc:~$ ^C
```

**Expected behavior**
Program installs and starts without errors about missing modules

**Desktop (please complete the following information):**
```
tobias@tobias-pc:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
tobias@tobias-pc:~$ cat /etc/debian_version
10.6
```

**Error Messages**
see logs from reproduce

**Comment by iwalton3** [comment]
https://github.com/iwalton3/jellyfin-mpv-shim/blob/master/README.md#linux-installation

**Comment by topas-rec** [comment]
@iwalton3 thanks for that installation help.
I think this should be done in one package to install.

I tried that - maybe I'm doing something wrong but i am not able to get 
`jellyfin-mpv-shim find `mpv`:

```
tobias@tobias-pc:~$ pip3 install --upgrade jellyfin-mpv-shim mpv
Collecting jellyfin-mpv-shim
  Using cached https://files.pythonhosted.org/packages/b0/9c/f54be0e96c9b10f5c570da0bb746e734d9e8eb9cf6c02bfd37d1fce1044b/jellyfin_mpv_shim-1.8.0-py3-none-any.whl
Collecting mpv
Requirement already satisfied, skipping upgrade: python-mpv-jsonipc>=1.1.9 in ./.local/lib/python3.7/site-packages (from jellyfin-mpv-shim) (1.1.11)
Requirement already satisfied, skipping upgrade: python-mpv in ./.local/lib/python3.7/site-packages (from jellyfin-mpv-shim) (0.5.2)
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python3/dist-packages (from jellyfin-mpv-shim) (2.21.0)
Requirement already satisfied, skipping upgrade: jellyfin-apiclient-python>=1.6.1 in ./.local/lib/python3.7/site-packages (from jellyfin-mpv-shim) (1.6.1)
Requirement already satisfied, skipping upgrade: urllib3 in /usr/lib/python3/dist-packages (from jellyfin-apiclient-python>=1.6.1->jellyfin-mpv-shim) (1.24.1)
Requirement already satisfied, skipping upgrade: websocket-client in ./.local/lib/python3.7/site-packages (from jellyfin-apiclient-python>=1.6.1->jellyfin-mpv-shim) (0.57.0)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3/dist-packages (from jellyfin-apiclient-python>=1.6.1->jellyfin-mpv-shim) (1.12.0)
Installing collected packages: jellyfin-mpv-shim, mpv
Successfully installed jellyfin-mpv-shim-1.8.0 mpv-0.1
tobias@tobias-pc:~$ sudo apt install python3-flask python3-webview python3-werkzeug
[sudo] password for tobias: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  fonts-wine libcapi20-3 libodbc1 libosmesa6 libvkd3d1 libwine wine64
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  python3-blinker python3-click python3-colorama python3-itsdangerous python3-jinja2
  python3-openssl python3-pyinotify python3-simplejson
Suggested packages:
  python-blinker-doc python-flask-doc python-jinja2-doc python-openssl-doc python3-openssl-dbg
  python-pyinotify-doc ipython3 python3-lxml python3-termcolor python3-watchdog
  python-werkzeug-doc
The following NEW packages will be installed:
  python3-blinker python3-click python3-colorama python3-flask python3-itsdangerous
  python3-jinja2 python3-openssl python3-pyinotify python3-simplejson python3-webview
  python3-werkzeug
0 upgraded, 11 newly installed, 0 to remove and 6 not upgraded.
Need to get 692 kB of archives.
After this operation, 3.054 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://deb.debian.org/debian buster/main amd64 python3-blinker all 1.4+dfsg1-0.2 [14,0 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 python3-colorama all 0.3.7-1 [18,1 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 python3-click all 7.0-1 [73,6 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 python3-itsdangerous all 0.24+dfsg1-2 [13,0 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 python3-jinja2 all 2.10-2 [106 kB]
Get:6 http://deb.debian.org/debian buster/main amd64 python3-werkzeug all 0.14.1+dfsg1-4+deb10u1 [196 kB]
Get:7 http://deb.debian.org/debian buster/main amd64 python3-flask all 1.0.2-3 [93,0 kB]
Get:8 http://deb.debian.org/debian buster/main amd64 python3-openssl all 19.0.0-1 [52,1 kB]
Get:9 http://deb.debian.org/debian buster/main amd64 python3-pyinotify all 0.9.6-1 [26,9 kB]
Get:10 http://deb.debian.org/debian buster/main amd64 python3-simplejson amd64 3.16.0-1 [60,7 kB]
Get:11 http://deb.debian.org/debian buster/main amd64 python3-webview all 2.3+dfsg-1 [38,3 kB]
Fetched 692 kB in 0s (2.911 kB/s)        
Selecting previously unselected package python3-blinker.
(Reading database ... 387938 files and directories currently installed.)
Preparing to unpack .../00-python3-blinker_1.4+dfsg1-0.2_all.deb ...
Unpacking python3-blinker (1.4+dfsg1-0.2) ...
Selecting previously unselected package python3-colorama.
Preparing to unpack .../01-python3-colorama_0.3.7-1_all.deb ...
Unpacking python3-colorama (0.3.7-1) ...
Selecting previously unselected package python3-click.
Preparing to unpack .../02-python3-click_7.0-1_all.deb ...
Unpacking python3-click (7.0-1) ...
Selecting previously unselected package python3-itsdangerous.
Preparing to unpack .../03-python3-itsdangerous_0.24+dfsg1-2_all.deb ...
Unpacking python3-itsdangerous (0.24+dfsg1-2) ...
Selecting previously unselected package python3-jinja2.
Preparing to unpack .../04-python3-jinja2_2.10-2_all.deb ...
Unpacking python3-jinja2 (2.10-2) ...
Selecting previously unselected package python3-werkzeug.
Preparing to unpack .../05-python3-werkzeug_0.14.1+dfsg1-4+deb10u1_all.deb ...
Unpacking python3-werkzeug (0.14.1+dfsg1-4+deb10u1) ...
Selecting previously unselected package python3-flask.
Preparing to unpack .../06-python3-flask_1.0.2-3_all.deb ...
Unpacking python3-flask (1.0.2-3) ...
Selecting previously unselected package python3-openssl.
Preparing to unpack .../07-python3-openssl_19.0.0-1_all.deb ...
Unpacking python3-openssl (19.0.0-1) ...
Selecting previously unselected package python3-pyinotify.
Preparing to unpack .../08-python3-pyinotify_0.9.6-1_all.deb ...
Unpacking python3-pyinotify (0.9.6-1) ...
Selecting previously unselected package python3-simplejson.
Preparing to unpack .../09-python3-simplejson_3.16.0-1_amd64.deb ...
Unpacking python3-simplejson (3.16.0-1) ...
Selecting previously unselected package python3-webview.
Preparing to unpack .../10-python3-webview_2.3+dfsg-1_all.deb ...
Unpacking python3-webview (2.3+dfsg-1) ...
Setting up python3-colorama (0.3.7-1) ...
Setting up python3-openssl (19.0.0-1) ...
Setting up python3-pyinotify (0.9.6-1) ...
Setting up python3-itsdangerous (0.24+dfsg1-2) ...
Setting up python3-click (7.0-1) ...
Setting up python3-simplejson (3.16.0-1) ...
Setting up python3-jinja2 (2.10-2) ...
Setting up python3-webview (2.3+dfsg-1) ...
Setting up python3-werkzeug (0.14.1+dfsg1-4+deb10u1) ...
Setting up python3-blinker (1.4+dfsg1-0.2) ...
Setting up python3-flask (1.0.2-3) ...
tobias@tobias-pc:~$ pip3 install pystray
Collecting pystray
  Downloading https://files.pythonhosted.org/packages/3d/af/b0f95d4533f642c1177542566c65a0172445b04cba25eb2f3870450e50ae/pystray-0.17.1-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 2.2MB/s 
Requirement already satisfied: python-xlib>=0.17; sys_platform == "linux" in /usr/lib/python3/dist-packages (from pystray) (0.23)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from pystray) (1.12.0)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from pystray) (5.4.1)
Installing collected packages: pystray
Successfully installed pystray-0.17.1
tobias@tobias-pc:~$ sudo apt install python3-tk
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-tk is already the newest version (3.7.3-1).
python3-tk set to manually installed.
The following packages were automatically installed and are no longer required:
  fonts-wine libcapi20-3 libodbc1 libosmesa6 libvkd3d1 libwine wine64
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
tobias@tobias-pc:~$ jellyfin-mpv-
jellyfin-mpv-desktop  jellyfin-mpv-shim     
tobias@tobias-pc:~$ jellyfin-mpv-desktop 
2020-11-23 18:24:33,628 [    INFO] conf: Loaded settings from json: /home/tobias/.config/jellyfin-mpv-shim/conf.json
2020-11-23 18:24:33,711 [ WARNING] player: Could not find libmpv1.
2020-11-23 18:24:33,712 [    INFO] player: Using external mpv playback backend.
2020-11-23 18:24:33,712 [   DEBUG] mpv-jsonipc: Staring MPV from mpv.
2020-11-23 18:24:33,712 [   DEBUG] mpv-jsonipc: Using IPC socket /tmp/mpv81719453658007 for MPV.
Traceback (most recent call last):
  File "/home/tobias/.local/bin/jellyfin-mpv-desktop", line 10, in <module>
    sys.exit(main_desktop())
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 106, in main_desktop
    main(desktop, cef)
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 42, in main
    from .webclient_view import WebviewClient
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/webclient_view/__init__.py", line 26, in <module>
    from ..player import playerManager
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/player.py", line 759, in <module>
    playerManager = PlayerManager()
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/player.py", line 151, in __init__
    loglevel=settings.mpv_log_level, **mpv_options)
  File "/home/tobias/.local/lib/python3.7/site-packages/python_mpv_jsonipc.py", line 411, in __init__
    self.mpv_process = MPVProcess(ipc_socket, mpv_location, **kwargs)
  File "/home/tobias/.local/lib/python3.7/site-packages/python_mpv_jsonipc.py", line 217, in __init__
    self.process = subprocess.Popen(args)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mpv': 'mpv'
^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
tobias@tobias-pc:~$ ^C
tobias@tobias-pc:~$ pip3 uninstall mpv
Uninstalling mpv-0.1:
  Would remove:
    /home/tobias/.local/lib/python3.7/site-packages/mpv-0.1.dist-info/*
    /home/tobias/.local/lib/python3.7/site-packages/mpv.py
Proceed (y/n)? 
Your response ('') was not one of the expected responses: y, n
Proceed (y/n)? y
  Successfully uninstalled mpv-0.1
tobias@tobias-pc:~$ sudo apt install mpv
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  fonts-wine libcapi20-3 libodbc1 libosmesa6 libvkd3d1 libwine wine64
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  phantomjs python3-pyxattr rtmpdump youtube-dl
Suggested packages:
  python3-pyxattr-dbg python-pyxattr-doc
The following NEW packages will be installed:
  mpv phantomjs python3-pyxattr rtmpdump youtube-dl
0 upgraded, 5 newly installed, 0 to remove and 6 not upgraded.
Need to get 2.357 kB of archives.
After this operation, 9.231 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://deb.debian.org/debian buster/main amd64 mpv amd64 0.29.1-1 [960 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 phantomjs amd64 2.1.1+dfsg-2 [302 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 python3-pyxattr amd64 0.6.1-1 [16,8 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 rtmpdump amd64 2.4+20151223.gitfa8646d.1-2 [51,3 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 youtube-dl all 2019.01.17-1.1 [1.027 kB]
Fetched 2.357 kB in 0s (4.717 kB/s)   
Selecting previously unselected package mpv.
(Reading database ... 388265 files and directories currently installed.)
Preparing to unpack .../mpv_0.29.1-1_amd64.deb ...
Unpacking mpv (0.29.1-1) ...
Selecting previously unselected package phantomjs.
Preparing to unpack .../phantomjs_2.1.1+dfsg-2_amd64.deb ...
Unpacking phantomjs (2.1.1+dfsg-2) ...
Selecting previously unselected package python3-pyxattr.
Preparing to unpack .../python3-pyxattr_0.6.1-1_amd64.deb ...
Unpacking python3-pyxattr (0.6.1-1) ...
Selecting previously unselected package rtmpdump.
Preparing to unpack .../rtmpdump_2.4+20151223.gitfa8646d.1-2_amd64.deb ...
Unpacking rtmpdump (2.4+20151223.gitfa8646d.1-2) ...
Selecting previously unselected package youtube-dl.
Preparing to unpack .../youtube-dl_2019.01.17-1.1_all.deb ...
Unpacking youtube-dl (2019.01.17-1.1) ...
Setting up youtube-dl (2019.01.17-1.1) ...
Setting up phantomjs (2.1.1+dfsg-2) ...
Setting up mpv (0.29.1-1) ...
Setting up rtmpdump (2.4+20151223.gitfa8646d.1-2) ...
Setting up python3-pyxattr (0.6.1-1) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for desktop-file-utils (0.23-4) ...
tobias@tobias-pc:~$ jellyfin-mpv-desktop 
2020-11-23 18:25:28,296 [    INFO] conf: Loaded settings from json: /home/tobias/.config/jellyfin-mpv-shim/conf.json
Traceback (most recent call last):
  File "/home/tobias/.local/bin/jellyfin-mpv-desktop", line 10, in <module>
    sys.exit(main_desktop())
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 106, in main_desktop
    main(desktop, cef)
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 42, in main
    from .webclient_view import WebviewClient
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/webclient_view/__init__.py", line 26, in <module>
    from ..player import playerManager
  File "/home/tobias/.local/lib/python3.7/site-packages/jellyfin_mpv_shim/player.py", line 36, in <module>
    import mpv
ModuleNotFoundError: No module named 'mpv'
```

**Comment by iwalton3** [comment]
The mpv package must be installed both through pip and apt. They are different packages.

**Comment by topas-rec** [comment]
> The mpv package must be installed both through pip and apt. They are different packages.

I found time to test this.
`jellyfin-mpv-desktop` started successfully
