### ISSUE TITLE
"Failed to execute script run-desktop" when using external mpv

### ISSUE THREAD

**Issue by siferati** [iwalton3/jellyfin-mpv-shim#156]
**Describe the bug**
When using external mpv, the desktop client crashes on start with the error *failed to execute script run-desktop*.

**To Reproduce**
1. Set `mpv_ext` to true.
2. Set `mpv_ext_path` to mpv path.
3. Open the desktop client.

**Expected behavior**
Desktop client should open normally.

**Desktop**
 - OS: Windows 10 Pro
 - Version 1909

**Logs**
```
2021-02-06 16:06:20,531 [    INFO] player: Using external mpv playback backend.
2021-02-06 16:06:20,531 [   DEBUG] mpv-jsonipc: Staring MPV from C:\Users\Tirafesi\Desktop\MPV\mpv.exe.
2021-02-06 16:06:20,531 [   DEBUG] mpv-jsonipc: Using IPC socket \\.\pipe\mpv110428743258104 for MPV.
2021-02-06 16:06:20,738 [   ERROR] mpv-jsonipc: MPV failed with returncode 1.
2021-02-06 16:06:20,738 [ WARNING] mpv-jsonipc: MPV start failed.
Traceback (most recent call last):
  File "python_mpv_jsonipc.py", line 418, in __init__
  File "python_mpv_jsonipc.py", line 242, in __init__
python_mpv_jsonipc.MPVError: MPV not started.
2021-02-06 16:06:20,738 [   DEBUG] mpv-jsonipc: Staring MPV from C:\Users\Tirafesi\Desktop\MPV\mpv.exe.
2021-02-06 16:06:20,738 [   DEBUG] mpv-jsonipc: Using IPC socket \\.\pipe\mpv110428743258104 for MPV.
2021-02-06 16:06:20,946 [   ERROR] mpv-jsonipc: MPV failed with returncode 1.
2021-02-06 16:06:20,946 [ WARNING] mpv-jsonipc: MPV start failed.
Traceback (most recent call last):
  File "python_mpv_jsonipc.py", line 418, in __init__
  File "python_mpv_jsonipc.py", line 242, in __init__
python_mpv_jsonipc.MPVError: MPV not started.
2021-02-06 16:06:20,946 [   DEBUG] mpv-jsonipc: Staring MPV from C:\Users\Tirafesi\Desktop\MPV\mpv.exe.
2021-02-06 16:06:20,946 [   DEBUG] mpv-jsonipc: Using IPC socket \\.\pipe\mpv110428743258104 for MPV.
2021-02-06 16:06:21,146 [   ERROR] mpv-jsonipc: MPV failed with returncode 1.
2021-02-06 16:06:21,146 [ WARNING] mpv-jsonipc: MPV start failed.
Traceback (most recent call last):
  File "python_mpv_jsonipc.py", line 418, in __init__
  File "python_mpv_jsonipc.py", line 242, in __init__
python_mpv_jsonipc.MPVError: MPV not started.
```

**Comment by iwalton3** [comment]
> MPV failed with returncode 1.

Seems to suggest MPV is refusing to start. It is hard to tell why because it is not able to connect and receive MPV's errors yet. You might try running MPV separately and setting the socket value in the config to see what happens.
