### ISSUE TITLE
No connection adapters were found for '*****:8096/Users/AuthenticateByName'

### ISSUE THREAD

**Issue by wanghuangjie** [iwalton3/jellyfin-mpv-shim#23]
**Describe the bug**

No connection adapters were found for '*****:8096/Users/AuthenticateByName

**Client**: MacOS 10.14 ,```pip3 install git+https://github.com/iwalton3/jellyfin-mpv-shim```

                  python 3.7.6_1 is already installed and up-to-date

                  mpv 0.32.0 is already installed and up-to-date

**Server**:Docker Lastest version of Jellyfin 

**To Reproduce**
```
2020-02-22 07:18:33,870 [    INFO] Loaded settings from json: /Users/wanghuangjie/Library/Application Support/jellyfin-mpv-shim/conf.json
2020-02-22 07:18:34,077 [   DEBUG] Staring MPV from mpv.
2020-02-22 07:18:34,077 [   DEBUG] Using IPC socket /tmp/mpv170904384311864 for MPV.
2020-02-22 07:18:34,668 [   DEBUG] STREAM b'IHDR' 16 13
2020-02-22 07:18:34,669 [   DEBUG] STREAM b'zTXt' 41 1315
2020-02-22 07:18:34,669 [   DEBUG] STREAM b'bKGD' 1368 6
2020-02-22 07:18:34,670 [   DEBUG] b'bKGD' 1368 6 (unknown)
2020-02-22 07:18:34,670 [   DEBUG] STREAM b'pHYs' 1386 9
2020-02-22 07:18:34,670 [   DEBUG] STREAM b'tIME' 1407 7
2020-02-22 07:18:34,671 [   DEBUG] b'tIME' 1407 7 (unknown)
2020-02-22 07:18:34,671 [   DEBUG] STREAM b'IDAT' 1426 612
2020-02-22 07:18:34.772 Python[24266:988965] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection invalid
2020-02-22 07:18:34.777 Python[24267:988995] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection invalid
2020-02-22 07:18:49,706 [   DEBUG] JellyfinClient initializing...
2020-02-22 07:18:49,707 [   DEBUG] Configuration initializing...
2020-02-22 07:18:49,707 [   DEBUG] Begin http constructor.
2020-02-22 07:18:49,707 [   DEBUG] WSClient initializing...
2020-02-22 07:18:49,707 [   DEBUG] ConnectionManager initializing...
2020-02-22 07:18:49,708 [   DEBUG] Credentials initializing...
2020-02-22 07:18:49,708 [   DEBUG] Begin app constructor.
2020-02-22 07:18:49,708 [    INFO] tryConnect url: http://192.168.1.10:8096/system/info/public
2020-02-22 07:18:49,718 [   DEBUG] Starting new HTTP connection (1): 192.168.1.10:8096
2020-02-22 07:18:49,727 [   DEBUG] http://192.168.1.10:8096 "GET /system/info/public HTTP/1.1" 200 None
2020-02-22 07:18:49,729 [    INFO] connectToAddress http://192.168.1.10:8096 succeeded
2020-02-22 07:18:49,729 [    INFO] begin connectToServer
2020-02-22 07:18:49,729 [    INFO] tryConnect url: http://192.168.1.10:8096/system/info/public
2020-02-22 07:18:49,732 [   DEBUG] Starting new HTTP connection (1): 192.168.1.10:8096
2020-02-22 07:18:49,740 [   DEBUG] http://192.168.1.10:8096 "GET /system/info/public HTTP/1.1" 200 None
2020-02-22 07:18:49,741 [    INFO] calling onSuccessfulConnection with server acepc
2020-02-22 07:18:49,741 [    INFO] None
2020-02-22 07:18:49,741 [ WARNING] invalid credentials format
2020-02-22 07:18:49,741 [   DEBUG] credentials initialized with: {}
2020-02-22 07:18:49,741 [   DEBUG] credentialsupdated
2020-02-22 07:18:49,742 [   ERROR] No connection adapters were found for '192.168.1.10:8096/Users/AuthenticateByName'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jellyfin_apiclient_python/connection_manager.py", line 196, in _request_url
    return self.http.request(request)
  File "/usr/local/lib/python3.7/site-packages/jellyfin_apiclient_python/http.py", line 95, in request
    r = self._requests(session or self.session or requests, data.pop('type', "GET"), **data, stream=stream)
  File "/usr/local/lib/python3.7/site-packages/jellyfin_apiclient_python/http.py", line 248, in _requests
    return session.post(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 640, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 731, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for '192.168.1.10:8096/Users/AuthenticateByName'
2020-02-22 07:18:49,743 [   ERROR] No connection adapters were found for '192.168.1.10:8096/Users/AuthenticateByName'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jellyfin_apiclient_python/connection_manager.py", line 111, in login
    result = self._request_url(request, False)
  File "/usr/local/lib/python3.7/site-packages/jellyfin_apiclient_python/connection_manager.py", line 196, in _request_url
    return self.http.request(request)
  File "/usr/local/lib/python3.7/site-packages/jellyfin_apiclient_python/http.py", line 95, in request
    r = self._requests(session or self.session or requests, data.pop('type', "GET"), **data, stream=stream)
  File "/usr/local/lib/python3.7/site-packages/jellyfin_apiclient_python/http.py", line 248, in _requests
    return session.post(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 640, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 731, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for '192.168.1.10:8096/Users/AuthenticateByName'
2020-02-22 07:18:49,744 [    INFO] Begin connect
2020-02-22 07:18:49,744 [    INFO] Begin getAvailableServers
2020-02-22 07:18:49,744 [   DEBUG] MultiGroup      : ('<broadcast>', 7359)
2020-02-22 07:18:49,744 [   DEBUG] Sending UDP Data: b'who is JellyfinServer?'
2020-02-22 07:18:50,748 [    INFO] Found Servers: []
2020-02-22 07:18:50,751 [   DEBUG] credentialsupdated
2020-02-22 07:18:50,751 [    INFO] Begin connectToServers, with 1 servers
2020-02-22 07:18:50,751 [    INFO] begin connectToServer
2020-02-22 07:18:50,751 [    INFO] tryConnect url: http://192.168.1.10:8096/system/info/public
2020-02-22 07:18:50,752 [   DEBUG] Starting new HTTP connection (1): 192.168.1.10:8096
2020-02-22 07:18:50,761 [   DEBUG] http://192.168.1.10:8096 "GET /system/info/public HTTP/1.1" 200 None
2020-02-22 07:18:50,762 [    INFO] calling onSuccessfulConnection with server acepc
2020-02-22 07:18:50,763 [   DEBUG] credentialsupdated
2020-02-22 07:18:50,763 [   DEBUG] resolving connectToServers with result['State']: {'Servers': [{'address': 'http://192.168.1.10:8096', 'Name': 'acepc', 'Id': '55df3aa284ff45c5b86e3787cfec638c', 'DateLastAccessed': '2020-02-22T07:18:50Z'}], 'State': 2}
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Error Messages**
Please provide the console output by clicking the systray icon and selecting "Show Console".

**Comment by iwalton3** [comment]
Did you enter "192.168.1.10:8096" into the Server box? Try using "http://192.168.1.10:8096".

**Comment by wanghuangjie** [comment]
> Did you enter "192.168.1.10:8096" into the Server box? Try using "http://192.168.1.10:8096".

yep,

**Comment by iwalton3** [comment]
The GUI components that appear to be failing shouldn't be loaded after the first time you use the application. I'd restart the program and try casting media to it. If that doesn't work, an easy workaround you could try would be to disable the GUI. You can do this by setting `enable_gui` to `false` in `Library/Application Support/jellyfin-mpv-shim/conf.json` or by uninstalling `pystray`.

There is an issue here that appears to be similar to what is happening for you: https://github.com/matplotlib/matplotlib/issues/14999

I don't have a computer running Mac OSX to test on unfortunately. It looks like some people were able to get it to work by downgrading python or upgrading their OS. (The version of OSX that you have and the person in that ticket have is the same.)

**Comment by wanghuangjie** [comment]
thanks for your help.
1. enable_gui change false.
2. pip3 uninstall pystray.
neither of them works.

**Comment by iwalton3** [comment]
I'm figuring you are launching the program from the terminal. Does the error `Python[26713:1112451] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection invalid` go away when you do that? Does the application work with the error message?

If the program is working, you should be able to select it from the cast menu. It has no user interface until you cast to it.

Click the cast icon: ![image](https://user-images.githubusercontent.com/8078788/75082778-4dee6580-54e3-11ea-95da-37c2f10706e5.png)

Then "Jellyfin MPV Shim" should appear in the list: ![image](https://user-images.githubusercontent.com/8078788/75082763-3adb9580-54e3-11ea-8e21-9d10e8989fca.png)

**Comment by wanghuangjie** [comment]
LOL! 
It works!
![image](https://user-images.githubusercontent.com/3711191/75082872-b45d9d00-5550-11ea-8ea3-57a21e722d24.png)
