### ISSUE TITLE
Not working with gnome-mpv/celluloid

### ISSUE THREAD

**Issue by MatthiasGrandl** [iwalton3/jellyfin-mpv-shim#61]
**Describe the bug**
When using the `mpv_ext` with celluloid (formerly gnome-mpv), gnome-mpv exits with the following `Unknown option --input-default-bindings=yes`

Entire output:
```
/home/foo/.local/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
2020-04-27 13:21:35,836 [    INFO] conf: Loaded settings from json: /home/foo/.config/jellyfin-mpv-shim/conf.json
2020-04-27 13:21:35,861 [    INFO] player: Using external mpv playback backend.
2020-04-27 13:21:35,862 [   DEBUG] mpv-jsonipc: Staring MPV from /usr/bin/gnome-mpv.
2020-04-27 13:21:35,862 [   DEBUG] mpv-jsonipc: Using IPC socket /tmp/mpv223943916870495 for MPV.
Unknown option --input-default-bindings=yes
2020-04-27 13:21:35,964 [   ERROR] mpv-jsonipc: MPV failed with returncode 1.
2020-04-27 13:21:35,964 [ WARNING] mpv-jsonipc: MPV start failed.
Traceback (most recent call last):
  File "/home/foo/.local/lib/python3.7/site-packages/python_mpv_jsonipc.py", line 385, in __init__
    self.mpv_process = MPVProcess(ipc_socket, mpv_location, **kwargs)
  File "/home/foo/.local/lib/python3.7/site-packages/python_mpv_jsonipc.py", line 215, in __init__
    raise MPVError("MPV not started.")
python_mpv_jsonipc.MPVError: MPV not started.
2020-04-27 13:21:35,965 [   DEBUG] mpv-jsonipc: Staring MPV from /usr/bin/gnome-mpv.
2020-04-27 13:21:35,965 [   DEBUG] mpv-jsonipc: Using IPC socket /tmp/mpv223943916870495 for MPV.
Unknown option --input-default-bindings=yes
2020-04-27 13:21:36,068 [   ERROR] mpv-jsonipc: MPV failed with returncode 1.
2020-04-27 13:21:36,069 [ WARNING] mpv-jsonipc: MPV start failed.
Traceback (most recent call last):
  File "/home/foo/.local/lib/python3.7/site-packages/python_mpv_jsonipc.py", line 385, in __init__
    self.mpv_process = MPVProcess(ipc_socket, mpv_location, **kwargs)
  File "/home/foo/.local/lib/python3.7/site-packages/python_mpv_jsonipc.py", line 215, in __init__
    raise MPVError("MPV not started.")
python_mpv_jsonipc.MPVError: MPV not started.
2020-04-27 13:21:36,069 [   DEBUG] mpv-jsonipc: Staring MPV from /usr/bin/gnome-mpv.
2020-04-27 13:21:36,069 [   DEBUG] mpv-jsonipc: Using IPC socket /tmp/mpv223943916870495 for MPV.
Unknown option --input-default-bindings=yes
2020-04-27 13:21:36,172 [   ERROR] mpv-jsonipc: MPV failed with returncode 1.
2020-04-27 13:21:36,172 [ WARNING] mpv-jsonipc: MPV start failed.
Traceback (most recent call last):
  File "/home/foo/.local/lib/python3.7/site-packages/python_mpv_jsonipc.py", line 385, in __init__
    self.mpv_process = MPVProcess(ipc_socket, mpv_location, **kwargs)
  File "/home/foo/.local/lib/python3.7/site-packages/python_mpv_jsonipc.py", line 215, in __init__
    raise MPVError("MPV not started.")
python_mpv_jsonipc.MPVError: MPV not started.
Traceback (most recent call last):
  File "/usr/bin/jellyfin-mpv-shim", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 54, in main
    from .player import playerManager
  File "/usr/lib/python3.7/site-packages/jellyfin_mpv_shim/player.py", line 551, in <module>
    playerManager = PlayerManager()
  File "/usr/lib/python3.7/site-packages/jellyfin_mpv_shim/player.py", line 103, in __init__
    **extra_options)
  File "/home/foo/.local/lib/python3.7/site-packages/python_mpv_jsonipc.py", line 391, in __init__
    raise MPVError("MPV process retry limit reached.")
python_mpv_jsonipc.MPVError: MPV process retry limit reached.
```

 - OS: Linux
 - Version 1.5.8

With `mpv_ext` set to false it works great, but I'd love to use `gnome-mpv`.

**Comment by iwalton3** [comment]
You can use `gnome-mpv` with MPV Shim, but you must launch `gnome-mpv` separately before MPV Shim. (`gnome-mpv` doesn't support the MPV command options directly.)

Configure MPV Shim with the following options (leave the other ones):
```json
{
    "mpv_ext": true,
    "mpv_ext_ipc": "/tmp/gmpv-socket",
    "mpv_ext_path": null,
    "mpv_ext_start": false,
    "enable_osc": false
}
```
Then within `gnome-mpv`, click the application icon (top left) > Preferences. Configure the following Extra MPV Options:
```
--idle --input-ipc-server=/tmp/gmpv-socket
```

**Comment by MatthiasGrandl** [comment]
Wow that was quick! Figured I was just missing something! Thanks so much! :)
