### ISSUE TITLE
Playback issues on Wayland

### ISSUE THREAD

**Issue by zoqaeski** [iwalton3/jellyfin-mpv-shim#76]
**Describe the bug**
Launching the application on GNOME Wayland has a variety of playback issues:

No window is spawned if it is launched using the Jellyfin MPV Shim launcher. The systemd journal reports the following output:
```
systemd[1462]: Started flatpak-com.github.iwalton3.jellyfin-mpv-shim-1950356.scope.
systemd[1462]: gnome-launched-com.github.iwalton3.jellyfin-mpv-shim.desktop-1950356.scope: Succeeded.
com.github.iwalton3.jellyfin-mpv-shim.desktop[1950460]: 2020-06-12 01:55:45,347 [    INFO] conf: Loaded settings from json: /home/faraday/.var/app/com.github.iwalton3.jellyfin-mpv-shim/config/jellyfin-mpv-shim/conf.json
com.github.iwalton3.jellyfin-mpv-shim.desktop[1950460]: 2020-06-12 01:55:55,860 [    INFO] player: Using libmpv1 playback backend.
com.github.iwalton3.jellyfin-mpv-shim.desktop[1950760]: Tk_Init error: no display name and no $DISPLAY environment variable
com.github.iwalton3.jellyfin-mpv-shim.desktop[1950760]: Process PreferencesWindowProcess-1:
com.github.iwalton3.jellyfin-mpv-shim.desktop[1950760]: Traceback (most recent call last):
com.github.iwalton3.jellyfin-mpv-shim.desktop[1950760]:   File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
com.github.iwalton3.jellyfin-mpv-shim.desktop[1950760]:     self.run()
com.github.iwalton3.jellyfin-mpv-shim.desktop[1950760]:   File "/app/lib/python3.7/site-packages/jellyfin_mpv_shim/gui_mgr.py", line 232, in run
com.github.iwalton3.jellyfin-mpv-shim.desktop[1950760]:     root = tk.Tk()
com.github.iwalton3.jellyfin-mpv-shim.desktop[1950760]:   File "/app/lib/python3.7/site-packages/tkinter/__init__.py", line 2023, in __init__
com.github.iwalton3.jellyfin-mpv-shim.desktop[1950760]:     self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
com.github.iwalton3.jellyfin-mpv-shim.desktop[1950760]: _tkinter.TclError: no display name and no $DISPLAY environment variable
com.github.iwalton3.jellyfin-mpv-shim.desktop[1950759]: 2020-06-12 01:56:07,494 [   DEBUG] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
com.github.iwalton3.jellyfin-mpv-shim.desktop[1950759]: 2020-06-12 01:56:07,495 [   DEBUG] PIL.PngImagePlugin: STREAM b'pHYs' 41 9
com.github.iwalton3.jellyfin-mpv-shim.desktop[1950759]: 2020-06-12 01:56:07,495 [   DEBUG] PIL.PngImagePlugin: STREAM b'IDAT' 62 709
```
If the Jellyfin MPV Desktop application launcher is used instead, video and audio playback don't start an MPV instance. The web player (?) is used instead, and Jellyfin transcodes videos if the file format isn't one supported natively by webkit.

**To Reproduce**
1. Open MPV Jellyfin (Shim|Desktop) on GNOME Wayland session

**Expected behavior**
MPV should be used for all video/audio playback. If I switch to an X11 session, it seems to work just fine (though there's still no systray).

**Desktop (please complete the following information):**
 - OS: Arch Linux, GNOME 3.36 
 - Version: Jellyfin MPV Shim 1.5.10, installed via Flatpak (Flathub)
 - MPV Version: 0.32.0

**Error Messages**
No systray support enabled in Flatpak.

**Comment by iwalton3** [comment]
It looks like the tkinter library doesn’t like Wayland. I’m not sure if there is a practical remediation for that, but you can always disable the systray in the config and use the cli mode instead.

For the desktop mode, I’d need the logs to be sure, but it sounds like the connection isn’t working. It may or may not be related to Wayland.

**Comment by zoqaeski** [comment]
I can provide the output from running the applications via flatpak instead of the desktop launchers.

`flatpak run com.github.iwalton3.jellyfin-mpv-shim --shim 2>&1 | tee mpv-shim.log` gives the following output, but no window is spawned and the application appears to hang, so I killed it with SIGTERM.
```
2020-06-14 02:13:05,085 [    INFO] conf: Loaded settings from json: /home/faraday/.var/app/com.github.iwalton3.jellyfin-mpv-shim/config/jellyfin-mpv-shim/conf.json
2020-06-14 02:13:05,117 [    INFO] player: Using libmpv1 playback backend.
Tk_Init error: no display name and no $DISPLAY environment variable
Process PreferencesWindowProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/app/lib/python3.7/site-packages/jellyfin_mpv_shim/gui_mgr.py", line 232, in run
    root = tk.Tk()
  File "/app/lib/python3.7/site-packages/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
2020-06-14 02:13:13,699 [   DEBUG] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
2020-06-14 02:13:13,699 [   DEBUG] PIL.PngImagePlugin: STREAM b'pHYs' 41 9
2020-06-14 02:13:13,699 [   DEBUG] PIL.PngImagePlugin: STREAM b'IDAT' 62 709

(jellyfin-mpv-desktop:14): Gtk-CRITICAL **: 02:13:14.472: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
xkbcommon: ERROR: Key "<LFSH>" added to modifier map for multiple modifiers; Using Lock, ignoring Shift
```

`flatpak run com.github.iwalton3.jellyfin-mpv-shim 2>&1 | tee mpv-shim-desktop.log` gives the next set of output. I can browse the media library in the Jellyfin server, but playing a file results in the web player being used rather than MPV, and this has a tendency to choke on large files.
```
2020-06-14 02:16:37,408 [    INFO] conf: Loaded settings from json: /home/faraday/.var/app/com.github.iwalton3.jellyfin-mpv-shim/config/jellyfin-mpv-shim/conf.json
2020-06-14 02:16:43,575 [    INFO] player: Using libmpv1 playback backend.
2020-06-14 02:16:49,258 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:16:49] "GET /index.html HTTP/1.1" 200 -
xkbcommon: ERROR: Key "<LFSH>" added to modifier map for multiple modifiers; Using Lock, ignoring Shift
xkbcommon: ERROR: Key "<LFSH>" added to modifier map for multiple modifiers; Using Lock, ignoring Shift
2020-06-14 02:16:58,996 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:16:58] "GET /index.html HTTP/1.1" 200 -
2020-06-14 02:16:59,418 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:16:59] "GET /serviceworker.js HTTP/1.1" 304 -
2020-06-14 02:17:00,734 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:00] "GET /strings/en-us.json?v=1592101020540 HTTP/1.1" 200 -
2020-06-14 02:17:15,239 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:15] "GET /bc04dcfae9be35c15d464498d584fe47.woff2 HTTP/1.1" 200 -
2020-06-14 02:17:15,788 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:15] "GET /084fe09b33731336dd69b0ab5e0c9e93.woff2 HTTP/1.1" 200 -
2020-06-14 02:17:15,898 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:15] "GET /692b4a8713a969ad5e335224fd6e8a0c.woff2 HTTP/1.1" 200 -
2020-06-14 02:17:16,002 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:16] "GET /cc2abb620d8eb513cfccf32ac27423c3.woff2 HTTP/1.1" 200 -
2020-06-14 02:17:16,014 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:16] "GET /ba515ce5be40eb5b651e9683528e59b3.woff2 HTTP/1.1" 200 -
2020-06-14 02:17:16,023 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:16] "GET /7c314dbd6c99a624d91751dac741eb41.woff2 HTTP/1.1" 200 -
2020-06-14 02:17:16,650 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:16] "GET /42a628a3a222f6b7da524c31914f6586.woff2 HTTP/1.1" 200 -
2020-06-14 02:17:16,877 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:16] "GET /029d9fb8d47ff1b030a1cfa45bdff885.woff2 HTTP/1.1" 200 -
2020-06-14 02:17:17,046 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:17] "GET /7cfcbea988b928ef930ea0730bcf2f11.woff2 HTTP/1.1" 200 -
2020-06-14 02:17:17,055 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:17] "GET /4f1ce5c1860a2d033d6f3bcda500d532.woff2 HTTP/1.1" 200 -
2020-06-14 02:17:17,068 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:17] "GET /38fef5b748050a6e608c591a56b05e66.woff2 HTTP/1.1" 200 -
2020-06-14 02:17:17,103 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:17] "GET /032a959c0b433591efb5c7b27b8efc32.woff2 HTTP/1.1" 200 -
2020-06-14 02:17:17,119 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:17] "GET /81a6c23254fa54a69440628d7e5b4f95.woff2 HTTP/1.1" 200 -
2020-06-14 02:17:17,131 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:17] "GET /fcff5075cf7d57c0370520c8671d938c.woff2 HTTP/1.1" 200 -
2020-06-14 02:17:17,142 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:17:17] "GET /1a86df20e76c27ce7055705abcbab247.woff2 HTTP/1.1" 200 -
2020-06-14 02:19:20,679 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:19:20] "GET /components/itemMediaInfo/itemMediaInfo.js?v=10.5.2-4 HTTP/1.1" 200 -
2020-06-14 02:19:20,791 [    INFO] werkzeug: 127.0.0.1 - - [14/Jun/2020 02:19:20] "GET /components/itemMediaInfo/itemMediaInfo.template.html?v=10.5.2-4 HTTP/1.1" 200 -
```
There's no errors or anything. MPV just doesn't load at all.

**Comment by iwalton3** [comment]
What happens if you disable the GUI in the config file (See README) and run shim mode from the command line?

**Comment by zoqaeski** [comment]
Nope, same result. Interestingly enough, on my laptop in a Wayland session, I get a second of audio playing before MPV quits with `[ERROR] mpv: vo/gpu/wayland: Error occurred on the display fd, closing`; on my desktop PC it falls back to the web player.

How can I get the flatpak version of this application to use my system mpv? Setting `mpv_ext` to true causes a file not found exception. I installed the flatpak version because I couldn't get the distro ([AUR](https://aur.archlinux.org/packages/jellyfin-mpv-shim/)) version to work _at all_.

**Comment by iwalton3** [comment]
> mpv_ext to true causes a file not found exception

Flatpak does package isolation, so it is unlikely you'll be able to get that to work. You could try installing via `pip`, see the README for details. I do not maintain the AUR package, so I can't really comment there.

**Comment by zoqaeski** [comment]
Installing via PIP (just locally with `pip install --user`) fixed the issue on both machines. MPV runs on Wayland, and no unnecessary transcoding takes place.

Whatever causes these issues for me is to do with the Flatpak version of the application.

**Comment by zx900930** [comment]
Can confirm the same problem under KDE Wayland, jellyfin-mpv-shim can't connect(no login page).

**Comment by ekirchman** [comment]
Sorry to revive an old thread, but I just wanted to chime and say that I haven't been having any issues when installing from pip. On Flatpak however, I do get the `Tk_Init error: no display name and no $DISPLAY environment variable` issue. Fedora 36 KDE Plasma
