### ISSUE TITLE
500 HTTP error when trying to start a stream

### ISSUE THREAD

**Issue by clearedTakeoff** [iwalton3/jellyfin-mpv-shim#79]
**Describe the bug**
I've just switched to Jellyfin and tried setting this up, however after adding the server and trying to start the stream the only response I'm getting is a 500 error in the console and nothing happens. After that the only way to try and start a stream again is to completely restart Jellyfin MPV Shim but nothing is changed.

**To Reproduce**
1. Start Jellyfin MPV Shim from the terminal using the command 'jellyfin-mpv-shim'
2. Add a remote server through http connection (also specifying the port number)
3. Open Jellyfin in web browser and select the device for casting
4. Try playing an arbitrary video in your library

**Expected behavior**
MPV opens and the video plays.

**Desktop (please complete the following information):**
 - OS: Linux Mint
- Version: 19.3

**Error Messages**
Here's how the console log looks like (I replaced the server url and port number in the log)

> 2020-06-19 18:04:11,542 [   DEBUG] event_handler: Handled Event Play: {'Id': '85c2a9ceb6f1068e5bd1e024df4d01c6', 'ItemIds': ['b5692c4e3f5ad73a33fd95e5f6f94842'], 'PlayCommand': 'PlayNow', 'ControllingUserId': 'e0d1797cacca45a9959cb2a818a28132', 'ServerId': '3b663704d5244f109719087a308d2f70'}
2020-06-19 18:04:11,614 [   DEBUG] urllib3.connectionpool: http://server_url:port_no "GET /jellyfin/Users/e0d1797cacca45a9959cb2a818a28132/Items/b5692c4e3f5ad73a33fd95e5f6f94842 HTTP/1.1" 200 None
2020-06-19 18:04:12,152 [   DEBUG] event_handler: EventHandler::playMedia <jellyfin_mpv_shim.media.Media object at 0x7f63ade021d0>
2020-06-19 18:04:12,152 [   DEBUG] media: Bandwidth: local=False, bitrate=None, force=False
2020-06-19 18:04:12,197 [   DEBUG] urllib3.connectionpool: http://server_url:port_no "POST /jellyfin/Items/b5692c4e3f5ad73a33fd95e5f6f94842/PlaybackInfo HTTP/1.1" 200 None
2020-06-19 18:04:12,200 [   DEBUG] media: Using direct url.
2020-06-19 18:04:12,286 [ WARNING] mpv: ffmpeg: http: HTTP error 500 Internal Server Error
2020-06-19 18:04:12,286 [   ERROR] mpv: stream: Failed to open http://server_url:port_no/jellyfin/Videos/b5692c4e3f5ad73a33fd95e5f6f94842/stream?static=true&MediaSourceId=b5692c4e3f5ad73a33fd95e5f6f94842&api_key=****.
2020-06-19 18:04:13,932 [    INFO] mpv: cplayer: 

The video does work if I try playing it inside the browser.

**Comment by iwalton3** [comment]
Please provide the server logs from Jellyfin, as this looks to be a server-side issue

**Comment by clearedTakeoff** [comment]
Completely forgot to check the server logs so on further inspection this is what the log says:

> [2020-06-19 18:04:12.269 +02:00] [ERR] [22] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://server_url:port_no/jellyfin/Videos/b5692c4e3f5ad73a33fd95e5f6f94842/stream?static=true&MediaSourceId=b5692c4e3f5ad73a33fd95e5f6f94842"
System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (131072 of 108).
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowTooManyBytesWritten(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.VerifyAndUpdateWrite(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FirstWriteAsyncInternal(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FirstWriteAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WritePipeAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.FileWriter.TransmitFile(Stream stream, String path, Int64 offset, Int64 count, FileShare fileShare, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.FileWriter.WriteToAsync(HttpResponse response, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-06-19 18:18:19.029 +02:00] [ERR] [40] App: AcceptWebSocketAsync error
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: Connection reset by peer
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Emby.Server.Implementations.SocketSharp.WebSocketSharpListener.ProcessWebSocketRequest(HttpContext ctx)

Searching for the cause of my issue brought me here https://github.com/jellyfin/jellyfin/issues/2354 which is the exact same issue as I described and the root of it seems to be that I'm using symlinks  for my video files instead of pointing Jellyfin to the original file. 

I'll close this issue since it looks like I'll have to wait for a Jellyfin patch to solve this.

**Comment by iwalton3** [comment]
If you want a workaround for this issue, you can use bindfs (with the `--resolve-symlinks` option) to dereference your symlinks. Just make your regular folder full of symlinks for whatever reason, and then use bindfs to mount another folder you use as the Jellyfin library.
