### ISSUE TITLE
OSX: event_handler: Unhandled Event WebSocketConnect: None

### ISSUE THREAD

**Issue by oliverwalton** [iwalton3/jellyfin-mpv-shim#82]
**Describe the bug**
When I run jellyfin-mpv-shim, it never gets running and freezes.

**To Reproduce**
1. install jellyfin-mpv-shim
2. run jellyfin-mpv-shim
3. error

**Expected behavior**
I expected it to start the program

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.15.5

**Error Messages**
2020-06-23 15:24:58,239 [    INFO] conf: Loaded settings from json: /Users/oliverwalton/Library/Application Support/jellyfin-mpv-shim/conf.json
2020-06-23 15:24:58,242 [ WARNING] root: Cannot load GUI. Falling back to command line interface.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jellyfin_mpv_shim/mpv_shim.py", line 37, in main
    from .gui_mgr import userInterface
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jellyfin_mpv_shim/gui_mgr.py", line 1, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
2020-06-23 15:24:58,257 [    INFO] player: Using external mpv playback backend.
2020-06-23 15:24:58,258 [   DEBUG] mpv-jsonipc: Staring MPV from mpv.
2020-06-23 15:24:58,260 [   DEBUG] mpv-jsonipc: Using IPC socket /tmp/mpv89364907576497 for MPV.
2020-06-23 15:24:58,576 [   DEBUG] mpv-jsonipc: Found MPV socket.
2020-06-23 15:24:58,599 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.client: JellyfinClient initializing...
2020-06-23 15:24:58,600 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Configuration initializing...
2020-06-23 15:24:58,600 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin http constructor.
2020-06-23 15:24:58,600 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.ws_client: WSClient initializing...
2020-06-23 15:24:58,600 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: ConnectionManager initializing...
2020-06-23 15:24:58,601 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: Credentials initializing...
2020-06-23 15:24:58,601 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin app constructor.
2020-06-23 15:24:58,601 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin connect
2020-06-23 15:24:58,601 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin getAvailableServers
2020-06-23 15:24:58,601 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: MultiGroup      : ('<broadcast>', 7359)
2020-06-23 15:24:58,601 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: Sending UDP Data: b'who is JellyfinServer?'
2020-06-23 15:24:59,603 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Found Servers: []
2020-06-23 15:24:59,603 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: credentialsupdated
2020-06-23 15:24:59,604 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: connect has 1 servers
2020-06-23 15:24:59,604 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: begin connectToServer
2020-06-23 15:24:59,604 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2020-06-23 15:24:59,604 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: 5
2020-06-23 15:24:59,641 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): URLTOMYSERVER
2020-06-23 15:24:59,714 [   DEBUG] urllib3.connectionpool: URLTOMYSERVER "GET //system/info/public HTTP/1.1" 200 None
2020-06-23 15:24:59,715 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: calling onSuccessfulConnection with server leon
2020-06-23 15:24:59,716 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info
2020-06-23 15:24:59,716 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: 5
2020-06-23 15:24:59,718 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): URLTOMYSERVER
2020-06-23 15:24:59,814 [   DEBUG] urllib3.connectionpool: URLTOMYSERVER "GET //system/info HTTP/1.1" 200 None
2020-06-23 15:24:59,818 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: credentialsupdated
2020-06-23 15:24:59,818 [    INFO] JELLYFIN.jellyfin_apiclient_python.client: User is authenticated.
2020-06-23 15:24:59,818 [   DEBUG] urllib3.util.retry: Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2020-06-23 15:24:59,818 [   DEBUG] urllib3.util.retry: Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2020-06-23 15:24:59,819 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: Websocket url: ws://URLTOMYSERVERANDSOMEMORESTUFF
2020-06-23 15:24:59,821 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): URLTOMYSERVER
2020-06-23 15:24:59,891 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: --->[ websocket ]
2020-06-23 15:24:59,892 [   DEBUG] urllib3.connectionpool: URLTOMYSERVER "POST //Sessions/Capabilities/Full HTTP/1.1" 204 0
2020-06-23 15:24:59,892 [   DEBUG] event_handler: Unhandled Event WebSocketConnect: None
2020-06-23 15:24:59,893 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.client: JellyfinClient initializing...
2020-06-23 15:24:59,894 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Configuration initializing...
2020-06-23 15:24:59,894 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin http constructor.
2020-06-23 15:24:59,894 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.ws_client: WSClient initializing...
2020-06-23 15:24:59,895 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: ConnectionManager initializing...
2020-06-23 15:24:59,895 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: Credentials initializing...
2020-06-23 15:24:59,895 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.configuration: Begin app constructor.
2020-06-23 15:24:59,895 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin connect
2020-06-23 15:24:59,895 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Begin getAvailableServers
2020-06-23 15:24:59,895 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: MultiGroup      : ('<broadcast>', 7359)
2020-06-23 15:24:59,895 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.connection_manager: Sending UDP Data: b'who is JellyfinServer?'
2020-06-23 15:25:00,896 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: Found Servers: []
2020-06-23 15:25:00,896 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: credentialsupdated
2020-06-23 15:25:00,896 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: connect has 1 servers
2020-06-23 15:25:00,896 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: begin connectToServer
2020-06-23 15:25:00,896 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info/public
2020-06-23 15:25:00,897 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: 5
2020-06-23 15:25:00,901 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): URLTOMYSERVER 
2020-06-23 15:25:00,974 [   DEBUG] urllib3.connectionpool: URLTOMYSERVER "GET //system/info/public HTTP/1.1" 200 None
2020-06-23 15:25:00,975 [    INFO] JELLYFIN.jellyfin_apiclient_python.connection_manager: calling onSuccessfulConnection with server leon
2020-06-23 15:25:00,975 [    INFO] JELLYFIN.jellyfin_apiclient_python.api: Sending get request to system/info
2020-06-23 15:25:00,976 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.api: 5
2020-06-23 15:25:00,979 [   DEBUG] urllib3.connectionpool: Starting new HTTP connection (1): URLTOMYSERVER
2020-06-23 15:25:01,080 [   DEBUG] urllib3.connectionpool: URLTOMYSERVER "GET //system/info HTTP/1.1" 200 None
2020-06-23 15:25:01,082 [   DEBUG] JELLYFIN.jellyfin_apiclient_python.credentials: credentialsupdated
2020-06-23 15:25:01,082 [    INFO] JELLYFIN.jellyfin_apiclient_python.client: User is authenticated.
2020-06-23 15:25:01,082 [   DEBUG] urllib3.util.retry: Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2020-06-23 15:25:01,083 [   DEBUG] urllib3.util.retry: Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2020-06-23 15:25:01,083 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: Websocket url: ws://URLTOMYSERVERPLUSSOCKETAPIANDSTUFF
2020-06-23 15:25:01,181 [    INFO] JELLYFIN.jellyfin_apiclient_python.ws_client: --->[ websocket ]
2020-06-23 15:25:01,181 [   DEBUG] event_handler: Unhandled Event WebSocketConnect: None
2020-06-23 15:25:01,187 [   DEBUG] urllib3.connectionpool:  URLTOMYSERVER "POST //Sessions/Capabilities/Full HTTP/1.1" 204 0

2020-06-23 15:25:49,685 [    INFO] root: Stopping services...

**Comment by iwalton3** [comment]
> it never gets running and freezes

You do not appear to have all of the dependencies installed for the GUI. You should still be able to cast to the application, as it does appear that the login was completed. (Assuming of course the "Stopping services..." line was caused by your pressing CTRL+C.)

If you would like to use the GUI, please make sure all of the needed dependencies are installed. For OSX, there is a separate procedure for installing the GUI, which required pyenv.

**Comment by oliverwalton** [comment]
the gui works fine, its the cli application that doesn't work

**Comment by iwalton3** [comment]
Are you able to see the CLI version from the web player? It only prompts for credentials if there aren't already any configured.

**Comment by iwalton3** [comment]
Does that last line "2020-06-23 15:25:49,685 [ INFO] root: Stopping services..." occur without any user intervention or was that from you pressing CTRL+C? If it occurred by itself, please re-open this and provide more details, as something would be seriously broken (and also fail to log) for that to happen.

The CLI version doesn't have an interface. It only asks for server connection details if it can't connect. You have to cast to the CLI version from another Jellyfin application, such as the web client. It appears as if the client is able to talk to the Jellyfin server and that you should be able to cast to it. If you cannot, please re-open the issue.
